resource "open77_admin"
version "0.5.1"
open77_version ">=0.0.1"
auto_start true
dependency "open77_contextmenu >=1.1.0"

-- Replacing a live CEF surface while gameplay is running has historically
-- caused unstable transitions, so every resource that owns one declares
-- "reconnect". There is no rules half here to protect from that: the panel IS
-- the resource, so a split would buy an export boundary nothing crosses.
reload_policy "reconnect"

-- Listed explicitly, one per line, never globbed. `server/**/*.lua` requires an
-- intermediate directory and matches nothing against a flat `server/main.lua`;
-- an empty glob stops the resource, and on the client side it refuses the WHOLE
-- session resource set with `script_pattern_empty:` and nobody can connect.
--
-- Manifest order IS load order (fixed 2026-08-26), and the server half reaches
-- across its files through one plain global, `Admin`, declared by main.lua. So
-- main.lua must come first.
shared_script "shared/config.lua"

-- The catalogue is SEVERAL files, and the order below is load order, which it
-- depends on: the head creates the table, the columns fill it, the index parts
-- read `records` and must come last. The last one asserts that all of them
-- ran, so a mistake here fails the resource loudly instead of shipping half a
-- catalogue.
--
-- It is split because the host aborts a script load that crosses 10 000 VM
-- instructions on a stalled frame, and rolls back the whole candidate resource
-- set when it does -- which reads as "my deploy did nothing" rather than as an
-- error. shared/catalog.lua carries the full note. Do not merge them, and do
-- not hand-edit them: tools/build-catalog.py emits this list.
shared_script "shared/catalog.lua"
shared_script "shared/catalog-records.lua"
shared_script "shared/catalog-names.lua"
shared_script "shared/catalog-taxonomy.lua"
shared_script "shared/catalog-attributes.lua"
shared_script "shared/catalog-index-1.lua"
shared_script "shared/catalog-index-2.lua"

-- The weapon catalogue: 189 records, generated by tools/build-weapons.py from
-- the 1925-record 2.31 extraction in docs/generated/weapons-2.31.csv.
--
-- ONE file, unlike the vehicle set above, and that is measured rather than
-- careless: the generator prints the load cost and it is ~1350 instructions
-- against the host's 10 000-instruction stride, where the 1372-record vehicle
-- catalogue cost ~13 700 and had to be split into seven. Same rule though --
-- do not hand-edit it, re-run the generator.
shared_script "shared/weapons.lua"

server_script "server/main.lua"
server_script "server/players.lua"
server_script "server/models-data.lua"
server_script "server/models.lua"
server_script "server/vehicles.lua"
server_script "server/bulk.lua"
server_script "server/world.lua"
server_script "server/props.lua"
server_script "server/weapons.lua"
server_script "server/public.lua"
server_script "server/developer.lua"

client_script "client/main.lua"

-- The compact keyboard menu (`/admin`). A SECOND client file and a SECOND
-- surface, and independent of client/main.lua on purpose: they share a Lua
-- state but not a line of code, so a fault in either leaves the other one
-- working. `kMaximumWebSurfaces` is 8, so two is well inside the budget.
--
-- Load order is manifest order, and this file reads `Open77AdminConfig`, which
-- shared/config.lua above declares. It must not move ahead of it.
client_script "client/doors.lua"
client_script "client/menu.lua"
client_script "client/coordinates.lua"
client_script "client/context.lua"

-- The manifest's own page, used when `WebUI.create` is called with no `entry`.
-- Both surfaces here name their entry explicitly (`web/index.html` and
-- `web/menu.html`); a `create` only succeeds for a file declared in `web_files`
-- below, which the `web/**` glob covers.
web_ui_page "web/index.html"
web_ui_auto_create false
web_files { "web/**" }

-- Least privilege, but honestly: an admin package needs most of the platform.
-- The manifest permission grants access to a BINDING; it never replaces the
-- per-call ACL check on `command.<name>`, which is what actually authorises an
-- operator. See docs and the resource README.
permissions {
    -- Read the server's compiled ACL for per-action availability and revocation.
    -- This is not an ACL writer and never replaces restricted command dispatch.
    "acl.read",
    -- Client: the pause key, so the panel closes with everything else.
    "local.events",

    -- Client: `Open77.input.isDown` / `isCaptured`, which is how the compact
    -- `/admin` menu is driven.
    --
    -- This grants a POLL of raw key state, and nothing else -- there is no
    -- binding to synthesise, consume or rebind a key anywhere in the API. The
    -- menu reads it precisely SO THAT it does not have to take focus: a focused
    -- surface would get the keys by swallowing them from the game, which is the
    -- failure this feature exists to avoid. `isCaptured` is the other half:
    -- when chat or the full panel legitimately owns the keyboard, the menu
    -- stands down instead of fighting for the arrow keys.
    "input.actions",
    -- Both halves: the panel's data channel and the travel/governor delegation.
    --
    -- It is also the ONLY grant the Weapons tab needs, which is worth stating
    -- because it looks like an omission. `Open77.weapons.*` on the SERVER is
    -- not a native: it is Lua in the host prelude that fires
    -- `open77:weapons:request` at one authenticated session and waits for
    -- `open77:weapons:result` -- so it is gated by `network.events` like every
    -- other server-to-client call and by nothing else. `player.weapons.read`
    -- and `player.weapons.edit` gate the CLIENT-side natives, which this
    -- package never touches: the work happens inside `open77_weapons`, whose
    -- own manifest declares them.
    "network.events",

    -- Server: the roster, life and health.
    "players.life.read",
    "players.model.read",
    "players.model.control",
    "players.life.kill",
    "players.life.revive",
    "players.life.respawn",
    "players.damage.read",
    "players.damage.apply",
    "players.stats.read",
    "players.stats.apply",
    "players.disconnect",
    "players.access", -- durable server-local bans; never an ACL role writer

    -- Server: spawning, removing, repairing, flags.
    "world.vehicles",

    -- Server: world props, lights and effects. Both bindings are read-open and
    -- write-scoped by the host: any resource may LIST every prop, and only the
    -- resource that created one may move, re-light or remove it. So these two
    -- grants buy the Props tab its own set dressing and nothing over anybody
    -- else's.
    "world.props",
    "world.effects",
    -- Read native door state for the local, ACL-authorised Developer inspector.
    "world.doors",

    -- Client: noclip / fly / direct teleport, delegated from an ACL-checked
    -- server command. The local lab commands are refused while a multiplayer
    -- session is active, so this is the only online path.
    "player.travel",

    -- Client: read streamed vehicles, and cap them.
    --
    -- `vehicles.performance` gates a native that landed after 2.31.0+op77.7 and
    -- is NOT in any shipped client. Declaring it is safe regardless: neither
    -- ResourceManifestParser.cs nor ResourceHost.cpp validates a permission
    -- name against a list, so an unknown name is inert rather than fatal.
    "vehicles.read",
    "vehicles.performance",

    -- Client: /admin.self.pos copies a transform the operator can paste.
    "clipboard.write"
}
